spring.application.name=reservation_service

#spring.datasource.url=jdbc:postgresql://postgresql-db-reservation:5432/reservation_db
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_db?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#user.service.url=http://user-service:8080
user.service.url=http://localhost:8081
#accommodation.service.url=http://accommodation-service:8080
accommodation.service.url=http://localhost:8082

server.port=8083